[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.24" }
annotations = { module = "org.jetbrains:annotations", version = "23.0.0" }
junit = { module = "org.junit.jupiter:junit-jupiter", version = "5.9.1" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.11.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
